### ISSUE TITLE
memorzdb: should/can i use them?

### ISSUE THREAD

**Issue by SerkanSipahi** [go-kivik/memorydb#5]
i want to use this memorydb for testing my kivik application. As i see this features: https://github.com/go-kivik/memorydb/blob/36bb6744b8b49179f1c4e5808ebb746b6cbc0fdb/test/test.go#L70-L84 are not implemented yet but it does not matter for me at the moment! 

So my questions:

1.) Should/Can i use them? why I say that? due https://github.com/flimzy/kivik/wiki/Kivik-database-drivers:
>MemoryDB github.com/go-kivik/memorydb Memory-only storage, for testing. (Under development)

2.) Is there any documentation for that except the well-written tests :)
3.) how would you test the performance? Setting up a real database but only for testing purposes?
4.) what do I still have to consider

Thank you.

**Comment by flimzy** [comment]
1. You are of course free to use the memorydb driver for testing. I do this myself. But, as indicated, it's not a complete implementation, so depending on what you need to test, it may or may not match your needs.

2. The Kivik project [compatibility table](https://github.com/flimzy/kivik/blob/master/doc/COMPATIBILITY.md) provides an at-a-glance list of completed functionality for all the official drivers, including this one.

3. Indeed. The only meaningful way to test performance of any system, is under real-world load.

4. Go makes it easy to test most systems (such as Kivik) using interfaces and minimal mocks, which may mean you don't need to use the memorydb driver for many of your tests.

Please let me know if I can provide further assistance.

**Comment by SerkanSipahi** [comment]
1.)I have to use the testsuite? https://github.com/go-kivik/memorydb/blob/36bb6744b8b49179f1c4e5808ebb746b6cbc0fdb/test/test.go#L13-L14 
What benefits i have with your Testsuite (https://github.com/go-kivik/kiviktest) (no documentation)?

2.) ... or can i just replace the "couch" driver with the "memorydb" and can use it in any test environment?
```golang
client, err := kivik.New(context.TODO(), "memorydb", "http://localhost:5984/")
if err != nil {
	panic(err)
}
```

**Comment by flimzy** [comment]
You should not have any reason to use the `kiviktest` test suite.  Just load load the `memorydb` module instead of `couchdb`:

    package main

    import (
        "context"

        "github.com/flimzy/kivik"
        _ "github.com/go-kivik/memorydb" // The Memory driver
    )

    func main() {
        client, err := kivik.New(context.TODO(), "memory", "")
        // ...
    }

**Comment by SerkanSipahi** [comment]
thank you :)
